name: CI/CD on Self-Hosted Runner

on:
  push:
    branches:
    - main



jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.SELF_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SELF_SECRET_KEY }}
        aws-region: "ap-south-1"
